"""
WPStateMachineDiagram - generate a Mermaid state diagram from the real transition table.

The diagram is built from WPAgentStateMachine().transitions, so it can never drift
from the code. Re-generate it whenever transitions change.

Two formats:
    colored  (default)  Mermaid flowchart; arrows are green for User commands, red for
                        Expert commands and grey for everything else (bypass/developer).
                        A plain stateDiagram cannot colour individual arrows.
    plain               Mermaid stateDiagram-v2 without colours.

Usage (from the WPAgent root):
    python3.12 -m utilities.WPStateMachineDiagram                      # print to stdout
    python3.12 -m utilities.WPStateMachineDiagram -o WPAgentStateMachine.mermaid
    python3.12 -m utilities.WPStateMachineDiagram --format plain
"""

import argparse
import sys
from collections import OrderedDict

from stateMachine.WpAgentStateMachine import WPAgentState, WPAgentStateMachine
from utilities.WPCommandConstants import EXPERT_COMMANDS, SEQUENCE_COMMANDS, USER_COMMANDS

ERROR_COMMAND = "Error"

# State changes that are NOT in the transition table: the login / logout actions
# (actions/WPLoginActions.py) set the state directly with force_state() / reset().
# (source, target, label, command used for the colour).  "AnyState" stands for every state.
ACTION_TRANSITIONS = [
    ("ServiceOn", "UserLogged", "UserLogIn", "UserLogIn"),
    ("ServiceOn", "UsedByDeveloper", "UserLogIn (Developer)", "UserLogIn"),
    ("AnyState", "UsedByDeveloper", "UserLogIn by a Developer takes control", "UserLogIn"),
    ("AnyState", "ServiceOn", "UserLogOut (resets the state)", "UserLogOut"),
]

# arrow colours by the lowest user level that may run the command
LEVEL_COLORS = {"user": "#2e7d32", "expert": "#c62828", "other": "#757575"}


def command_level(command: str) -> str:
    """'user' / 'expert' for classified commands, 'other' for the rest (bypass, developer)."""
    if command in USER_COMMANDS:
        return "user"
    if command in EXPERT_COMMANDS:
        return "expert"
    return "other"


def edge_label(commands) -> str:
    """Comma-joined command names; the built-in sequences are shown as one entry."""
    shown = [c for c in commands if c not in SEQUENCE_COMMANDS]
    if len(shown) < len(commands):
        shown.append("TakeImage* / BrightnessCorrection sequences")
    return ", ".join(shown)


def _error_note(sm, error_sources) -> str:
    all_states = [s for s in WPAgentState if s.name != "Error"]
    if all(s in error_sources for s in all_states):
        who = "Every state"
    else:
        who = ", ".join(s.name for s in error_sources)
    return f"{who} moves to Error when a command fails."


def build_mermaid(state_machine=None, style: str = "colored") -> str:
    """Return the state machine as Mermaid text. style: 'colored' (flowchart) or 'plain' (stateDiagram-v2)."""
    if style == "plain":
        return _build_state_diagram(state_machine)
    if style == "colored":
        return _build_flowchart(state_machine)
    raise ValueError(f"unknown style: {style!r}")


def _build_flowchart(state_machine=None) -> str:
    sm = state_machine or WPAgentStateMachine()

    # One edge per (source, target, level): commands of the same level share an arrow.
    edges = OrderedDict()
    error_sources = []
    for src, table in sm.transitions.items():
        for command, dst in table.items():
            if command == ERROR_COMMAND:
                error_sources.append(src)
                continue
            edges.setdefault((src.name, dst.name, command_level(command)), []).append(command)

    lines = [
        "%% Generated by utilities/WPStateMachineDiagram.py - do not edit by hand",
        "flowchart LR",
        "    START(( )) --> " + sm.current_state.name,
    ]
    link_styles = ["    linkStyle 0 stroke:#000000"]  # the start arrow
    index = 0
    # login / logout first, then the transition table
    for src, dst, label, command in ACTION_TRANSITIONS:
        index += 1
        node = 'AnyState(["Any state"])' if src == "AnyState" else src
        lines.append(f'    {node} -->|"{label}"| {dst}')
        color = LEVEL_COLORS[command_level(command)]
        link_styles.append(f"    linkStyle {index} stroke:{color},color:{color}")
    for (src, dst, level), commands in edges.items():
        index += 1
        lines.append(f'    {src} -->|"{edge_label(commands)}"| {dst}')
        color = LEVEL_COLORS[level]
        link_styles.append(f"    linkStyle {index} stroke:{color},color:{color}")

    if error_sources:
        lines.append(f'    ErrorNote>"{_error_note(sm, error_sources)}"] -.- Error')
        link_styles.append(
            f"    linkStyle {index + 1} stroke:#9e9e9e,stroke-dasharray:4"
        )

    lines += [
        "    subgraph Legend",
        '        LegendUser["User command"]',
        '        LegendExpert["Expert command"]',
        '        LegendOther["Other (bypass / developer)"]',
        "    end",
        "    style START fill:#000000,stroke:#000000",
        f"    style LegendUser stroke:{LEVEL_COLORS['user']},color:{LEVEL_COLORS['user']}",
        f"    style LegendExpert stroke:{LEVEL_COLORS['expert']},color:{LEVEL_COLORS['expert']}",
        f"    style LegendOther stroke:{LEVEL_COLORS['other']},color:{LEVEL_COLORS['other']}",
    ]
    return "\n".join(lines + link_styles) + "\n"


def _build_state_diagram(state_machine=None) -> str:
    """Return the state machine as a Mermaid ``stateDiagram-v2`` string (no colours)."""
    sm = state_machine or WPAgentStateMachine()
    transitions = sm.transitions

    # Group commands that share the same source and target into one edge.
    edges = OrderedDict()
    error_sources = []
    for src, table in transitions.items():
        for command, dst in table.items():
            if command == ERROR_COMMAND:
                error_sources.append(src)
                continue
            edges.setdefault((src.name, dst.name), []).append(command)

    lines = [
        "%% Generated by utilities/WPStateMachineDiagram.py - do not edit by hand",
        "stateDiagram-v2",
        "    direction LR",
        f"    [*] --> {sm.current_state.name}",
        '    state "Any state" as AnyState',
    ]
    for src, dst, label, _ in ACTION_TRANSITIONS:
        lines.append(f"    {src} --> {dst}: {label}")
    for (src, dst), commands in edges.items():
        lines.append(f"    {src} --> {dst}: {edge_label(commands)}")

    # An 'Error' transition exists from (almost) every state: draw it as one note
    # instead of one arrow per state.
    if error_sources:
        lines += [
            "    note right of Error",
            f"        {_error_note(sm, error_sources)}",
            "    end note",
        ]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate a Mermaid diagram of the WPAgent state machine")
    parser.add_argument("-o", "--output", help="write to this file instead of stdout")
    parser.add_argument(
        "--format", choices=["colored", "plain"], default="colored",
        help="colored: flowchart with green/red arrows (default); plain: stateDiagram-v2",
    )
    args = parser.parse_args(argv)

    diagram = build_mermaid(style=args.format)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(diagram)
        print(f"Wrote {args.output}")
    else:
        sys.stdout.write(diagram)
    return 0


if __name__ == "__main__":
    sys.exit(main())
