"""
WPStateMachineDiagram - generate a Mermaid state diagram from the real transition table.

The diagram is built from WPAgentStateMachine().transitions, so it can never drift
from the code. Re-generate it whenever transitions change.

Usage (from the WPAgent root):
    python3.12 -m utilities.WPStateMachineDiagram                      # print to stdout
    python3.12 -m utilities.WPStateMachineDiagram -o WPAgentStateMachine.mermaid
"""

import argparse
import sys
from collections import OrderedDict

from stateMachine.WpAgentStateMachine import WPAgentState, WPAgentStateMachine

ERROR_COMMAND = "Error"


def build_mermaid(state_machine=None) -> str:
    """Return the state machine as a Mermaid ``stateDiagram-v2`` string."""
    sm = state_machine or WPAgentStateMachine()
    transitions = sm.transitions

    # Group commands that share the same source and target into one edge.
    edges = OrderedDict()
    error_sources = []
    for src, table in transitions.items():
        for command, dst in table.items():
            if command == ERROR_COMMAND:
                error_sources.append(src)
                continue
            edges.setdefault((src.name, dst.name), []).append(command)

    lines = [
        "%% Generated by utilities/WPStateMachineDiagram.py - do not edit by hand",
        "stateDiagram-v2",
        "    direction LR",
        f"    [*] --> {sm.current_state.name}",
    ]
    for (src, dst), commands in edges.items():
        lines.append(f"    {src} --> {dst}: {', '.join(commands)}")

    # An 'Error' transition exists from (almost) every state: draw it as one note
    # instead of one arrow per state.
    if error_sources:
        all_states = [s for s in WPAgentState if s.name != "Error"]
        if all(s in error_sources for s in all_states):
            who = "Every state"
        else:
            who = ", ".join(s.name for s in error_sources)
        lines += [
            "    note right of Error",
            f"        {who} moves to Error when a command fails.",
            "    end note",
        ]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Generate a Mermaid diagram of the WPAgent state machine")
    parser.add_argument("-o", "--output", help="write to this file instead of stdout")
    args = parser.parse_args(argv)

    diagram = build_mermaid()
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(diagram)
        print(f"Wrote {args.output}")
    else:
        sys.stdout.write(diagram)
    return 0


if __name__ == "__main__":
    sys.exit(main())
