services:
  svt.db-agent:
    image: localhost/svt.db-agent:latest
    build:
      context: . # The directory containing your Dockerfile
      target: db-agent-entry
    network_mode: "host"
    volumes:
      - /tmp:/tmp
