services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: svt-zookeeper-dev
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: svt-kafka-broker--dev
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      # Bind to ALL interfaces, not just localhost
      - "9094:9094" # Internal (inter-container)
      - "9095:9095" # Tunnel (ssh )
      - "9096:9096" # External (internal network)
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,TUNNEL://localhost:9095,OUTSIDE://svmithi02.cern.ch:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,TUNNEL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,TUNNEL://0.0.0.0:9095,OUTSIDE://0.0.0.0:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: svt-kafka-ui-dev
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8087:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094

  svt.db-agent:
    image: ycorrales/svt.db-agent:release
    container_name: svt.db-agent-dev
    pull_policy: always # Forces a pull every time 'up' is run
    platform: linux/amd64 # Forces the use of the x86_64 version
    depends_on:
      - kafka
    networks:
      - kafka-network
    command: ["/app/configs/SvtDbAgent_config-dev.json"]
    restart: always
    environment:
      SVT_DB_AGENT_KAFKA_SERVER: kafka
      SVT_DB_AGENT_KAFKA_PORT: 9094
    volumes:
      - /tmp:/tmp

networks:
  kafka-network:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 172.21.0.0/16
        - subnet: 2001:db9::/32
