#CREATE SEQUENCE TEST3_VERSION_ID_SEQ START WITH 1;
CREATE TABLE TEST_VERSION_ID_SEQ (
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID)
);
INSERT INTO TEST_VERSION_ID_SEQ VALUES (NULL);

CREATE TABLE TEST_VERSION (
	ID INT,
	NAME VARCHAR(50),
	BASE_VERSION INT,
	CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DESCRIPTION VARCHAR(200),
	PRIMARY KEY(ID),
	FOREIGN KEY(BASE_VERSION) REFERENCES TEST_VERSION(ID)
);

CREATE TABLE TEST_VERSION_LOAD_HISTORY (
	VERSION_ID INT,
	LOAD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(VERSION_ID) REFERENCES TEST_VERSION(ID)
);

CREATE TABLE TEST_WAFER (
	ID INT NOT NULL AUTO_INCREMENT,
	SERIAL_NUM INT,
	SCANNED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DESCRIPTION VARCHAR(200),
	PRIMARY KEY (ID)
);
