--Create schema
CREATE SCHEMA IF NOT EXISTS prod;
-- SELECT SCHEMA
SET search_path TO Prod;

DROP TABLE "WaferType" CASCADE;
DROP TABLE "Wafer" CASCADE;
DROP TABLE "WaferLocation" CASCADE;
DROP TABLE "WaferTypeImage" CASCADE;
DROP TABLE "Asic" CASCADE;
