--Create schema
CREATE SCHEMA IF NOT EXISTS prod;
-- SELECT SCHEMA
SET search_path TO Prod;

CREATE TABLE IF NOT EXISTS WaferType (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) UNIQUE,
  engineeringRun "engineeringRun",
  foundry "foundryName",
  technology "waferTech",
  waferMap JSON
);

CREATE TABLE IF NOT EXISTS WaferTypeImage (
  waferTypeId integer NOT NULL,
  imageBase64String text NOT NULL,
  FOREIGN KEY (waferTypeId) REFERENCES WaferType (id)
);

CREATE TABLE IF NOT EXISTS Wafer (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serialNumber varchar(50) UNIQUE,
  batchNumber integer,
  generalLocation "wpGeneralLocation",
  thinningDate date,
  dicingDate date,
  productionDate date,
  waferTypeId integer NOT NULL,
  FOREIGN KEY (waferTypeId) REFERENCES WaferType (id)
);

CREATE TABLE IF NOT EXISTS WaferLocation (
  waferId integer NOT NULL,
  generalLocation "wpGeneralLocation",
  creationTime timestamp DEFAULT (CURRENT_TIMESTAMP),
  username varchar(50),
  description text,
  FOREIGN KEY (waferId) REFERENCES Wafer (id)
);

-- CREATE TABLE IF NOT EXISTS "Version" (
--   "id" integer PRIMARY KEY,
--   "name" varchar(50),
--   "baseVersion" integer,
--   "creationTime" timestamp DEFAULT (CURRENT_TIMESTAMP),
--   "description" varchar(50)
-- );

CREATE TABLE IF NOT EXISTS Asic (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  waferId integer,
  serialNumber varchar(50) UNIQUE,
  familyType "asicFamilyType",
  waferMapPosition varchar(50),
  quality "asicQuality",
  FOREIGN KEY (waferId) REFERENCES Wafer (id)
);

-- CREATE TABLE IF NOT EXISTS "ProbeCard" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "serialNumber" varchar(50) UNIQUE,
--   "vendor" pcVendor,
--   "name" pcName,
--   "model" pcModel,
--   "version" integer,
--   "arrivalDate" date,
--   "location" pcLocation,
--   "type" pcType,
--   "vendorCleaningInterval" integer
-- );
--
-- CREATE TABLE IF NOT EXISTS "ProbeCardFamilyType" (
--   "probeCardId" integer,
--   "asicFamilyType" asicFamilyType
-- );
--
-- CREATE TABLE IF NOT EXISTS "WaferProbeMachine" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "serialNumber" varchar(50) UNIQUE,
--   "name" varchar(50) UNIQUE,
--   "hostName" varchar(50),
--   "connectionType" wpConnectionType,
--   "connectionPort" integer,
--   "generalLocation" wpGeneralLocation,
--   "software" wpSwType,
--   "swVersion" varchar(50),
--   "vendor" wpVendor
-- );
--
-- CREATE TABLE IF NOT EXISTS "WaferProbeProject" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "wpMachineId" integer,
--   "waferTypeId" integer,
--   "asicFamilyType" asicFamilyType,
--   "orientation" waferMapOrientation,
--   "name" varchar(50) UNIQUE,
--   "alignmentDie" varchar(50),
--   "homeDie" varchar(50),
--   "local2GlobalMap" JSON
-- );
--
-- CREATE TABLE IF NOT EXISTS "ProbeCardMaintenance" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "probeCardId" integer,
--   "cleaningDate" date,
--   "totNumContacts" integer,
--   "numContactsSinceLastCleaning" integer,
--   "numContactsDuringCleaning" integer,
--   "cleaningOverdrive" integer
-- );
--
-- CREATE TABLE IF NOT EXISTS "AsicProbing" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "asicId" integer,
--   "numContacts" integer,
--   "mechanicalQuality" contactMechanicalQuality,
--   "arrivalDate" date
-- );
--
-- CREATE TABLE IF NOT EXISTS "WaferLoadedInMachine" (
--   "machineId" integer,
--   "waferId" integer,
--   "date" date,
--   "userName" varchar(50),
--   "status" waferInMachineStatus
-- );
--
-- CREATE TABLE IF NOT EXISTS "ProbeCardInstalledInMachine" (
--   "machineId" integer,
--   "probeCardId" integer,
--   "date" date,
--   "userName" varchar(50)
-- );
--
-- CREATE TABLE IF NOT EXISTS "AsicConfiguration" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "probeStationId" integer,
--   "versionId" integer,
--   "isTestingAllowed" boolean
-- );
--
-- CREATE TABLE IF NOT EXISTS "WpConfiguration" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "wpMachineId" integer,
--   "versionId" integer,
--   "orientation" waferMapOrientation
-- );
--
-- CREATE TABLE IF NOT EXISTS "ProbeCardConfiguration" (
--   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "probeCardId" integer,
--   "versionId" integer,
--   "cleaningInterval" integer
-- );
