\set SchemaName %SCHEMA_NAME%
--Create schema
CREATE SCHEMA IF NOT EXISTS :SchemaName;
-- SELECT SCHEMA
SET search_path TO :SchemaName;

DROP TABLE WaferType CASCADE;
DROP TABLE Wafer CASCADE;
DROP TABLE WaferLocation CASCADE;
DROP TABLE WaferTypeImage CASCADE;
DROP TABLE Asic CASCADE;
