#!/usr/bin/env python3
"""Generate the ITS3 TestAgent Kafka contract from the command registry.

    python3 contract/generate_contract.py

Reads ``service/commands.py`` + ``service/models.py`` and writes
``contract/svt.its3-test-agent.kafka.yaml`` — an OpenAPI 3.0 document
describing the Kafka message contract, in the same style as
``WPAgent/svt.wp-agent.yaml`` and ``TestAgent/docs/svt.test-agent.kafka``.

The YAML is generated output: never hand-edit it.  Change the Pydantic models
or the registry and re-run this script.

Pydantic emits JSON Schema 2020-12; OpenAPI 3.0 only accepts a subset of it, so
``_openapi_30()`` down-converts (``anyOf[X, null]`` -> ``nullable``, etc.).
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pydantic import BaseModel  # noqa: E402

from service.commands import COMMANDS  # noqa: E402
from service.models import (  # noqa: E402
    ReplyError,
    ReplyMessage,
    ReplyStatus,
    RequestMessage,
)
from service.topics import (  # noqa: E402
    HEARTBEAT_TOPIC,
    REPLY_TOPIC,
    REQUEST_TOPIC,
    STATUS_TOPIC,
)

CONTRACT_VERSION = "0.1.0"
OUTPUT = Path(__file__).resolve().parent / "svt.its3-test-agent.kafka.yaml"

DESCRIPTION = f"""
The Kafka message contract for the **ITS3 TestAgent** — the agent that drives a
full wafer test run (mosaix sequences + WPAgent prober moves) from a config and
a CSV run list.

### How to read this document
- Paths are `/<KAFKA_TOPIC>/<MESSAGE_TYPE>`, not HTTP routes. Nothing here is
  served over HTTP.
- The **request body** is the message you publish to `{REQUEST_TOPIC}`.
- The **200 response** is the message emitted to `{REPLY_TOPIC}` (or to the
  topic named by the request's `kafka_replyTopic` header).

### Topics
| Topic | Purpose |
|---|---|
| `{REQUEST_TOPIC}` | commands in |
| `{REPLY_TOPIC}` | replies out |
| `{HEARTBEAT_TOPIC}` | `{{timestamp, agent}}` every 2s; treat a beat older than 6s as down |
| `{STATUS_TOPIC}` | reserved for per-chip progress streaming — not produced yet, poll `GetStatus` |

### Headers (see SvtKafkaConventions.md)
- `kafka_correlationId` — UUID; echoed back on the reply so you can match it.
- `kafka_replyTopic` — where to send the reply.
- `kafka_replyPartition` — partition of the reply topic.

### Notes
- Only **one run** exists at a time (the prober and DAQ are exclusive):
  `StartRun` while a run is active is rejected with `BadRequest`.
- `StartRun` returns as soon as the run is *accepted*; poll `GetStatus` for
  progress.
- `StopRun` returns once the stop is *requested*; the agent still parks the
  prober and logs out before reaching a terminal state.

### Useful links
- Online Swagger Editor: https://editor-next.swagger.io
- SVT Kafka Naming Conventions:
  https://github.com/SVT-WP2/SVTSW/blob/master/Documentation/Kafka/SvtKafkaConventions.md

_Generated by `contract/generate_contract.py` — do not edit by hand._
""".strip()


# ---------------------------------------------------------------------------
# JSON Schema 2020-12 -> OpenAPI 3.0 subset
# ---------------------------------------------------------------------------

def _openapi_30(node):
    if isinstance(node, list):
        return [_openapi_30(n) for n in node]
    if not isinstance(node, dict):
        return node

    node = {k: _openapi_30(v) for k, v in node.items()}

    # `X | None` -> anyOf[X, {type: null}];  3.0 has no `type: null`.
    if "anyOf" in node:
        variants = node["anyOf"]
        non_null = [v for v in variants if v.get("type") != "null"]
        if len(non_null) < len(variants):
            node.pop("anyOf")
            node["nullable"] = True
            if len(non_null) == 1:
                only = non_null[0]
                # In 3.0 a `$ref` ignores sibling keys — wrap so `nullable` sticks.
                if "$ref" in only and len(only) == 1:
                    node["allOf"] = [only]
                else:
                    node.update(only)
            elif non_null:
                node["anyOf"] = non_null

    if "const" in node:  # 3.0 has no `const`
        node["enum"] = [node.pop("const")]

    # 2020-12 `examples: [...]` -> 3.0 `example: ...`
    examples = node.get("examples")
    if isinstance(examples, list) and examples:
        node.pop("examples")
        node["example"] = examples[0]

    return node


def _add_model(model: type[BaseModel], schemas: dict) -> str:
    """Register ``model`` (and anything it references) in components/schemas."""
    js = model.model_json_schema(ref_template="#/components/schemas/{model}")
    for name, sub in js.pop("$defs", {}).items():
        schemas.setdefault(name, _openapi_30(sub))
    schemas[model.__name__] = _openapi_30(js)
    return f"#/components/schemas/{model.__name__}"


def _example_of(model: type[BaseModel]) -> dict:
    extra = model.model_config.get("json_schema_extra") or {}
    return extra.get("example", {}) if isinstance(extra, dict) else {}


# ---------------------------------------------------------------------------
# Document
# ---------------------------------------------------------------------------

def build_spec() -> dict:
    schemas: dict = {}
    for envelope in (RequestMessage, ReplyMessage, ReplyError):
        _add_model(envelope, schemas)

    paths: dict = {}
    tags: dict[str, None] = {}

    for name, spec in COMMANDS.items():
        req_ref   = _add_model(spec.request, schemas)
        reply_ref = _add_model(spec.reply, schemas)
        for tag in spec.tags:
            tags[tag] = None

        request_example = {"type": name, "data": _example_of(spec.request)}

        paths[f"/{REQUEST_TOPIC}/{name}"] = {
            "post": {
                "tags":        list(spec.tags),
                "operationId": name,
                "summary":     spec.summary,
                "description": (spec.request.__doc__ or spec.summary).strip(),
                "requestBody": {
                    "required": True,
                    "content": {"application/json": {
                        "schema": {"allOf": [
                            {"$ref": "#/components/schemas/RequestMessage"},
                            {"type": "object", "properties": {
                                "type": {"type": "string", "enum": [name]},
                                "data": {"$ref": req_ref},
                            }},
                        ]},
                        "example": request_example,
                    }},
                },
                "responses": {
                    "200": {
                        "description": f"Message emitted to `{REPLY_TOPIC}`.",
                        "content": {"application/json": {
                            "schema": {"allOf": [
                                {"$ref": "#/components/schemas/ReplyMessage"},
                                {"type": "object", "properties": {
                                    "type": {"type": "string",
                                             "enum": [f"{name}Reply"]},
                                    "data": {"$ref": reply_ref},
                                }},
                            ]},
                            "examples": {
                                "success": {
                                    "summary": "Command accepted",
                                    "value": {
                                        "type": f"{name}Reply",
                                        "status": ReplyStatus.Success.value,
                                        "data": _example_of(spec.reply),
                                    },
                                },
                                "error": {
                                    "summary": "Command rejected",
                                    "value": {
                                        "type": f"{name}Reply",
                                        "status": ReplyStatus.BadRequest.value,
                                        "error": {"message": "…reason…"},
                                    },
                                },
                            },
                        }},
                    },
                },
            },
        }

    return {
        "openapi": "3.0.3",
        "info": {
            "title": "SVT ITS3 TestAgent (Kafka Command Contract)",
            "version": CONTRACT_VERSION,
            "description": DESCRIPTION,
        },
        "servers": [{
            "url": f"kafka://localhost:9092/{REQUEST_TOPIC}",
            "description": "Kafka request topic",
        }],
        "tags": [{"name": t} for t in tags],
        "paths": paths,
        "components": {"schemas": schemas},
    }


def _block_style_str(dumper, data):
    """Render multi-line strings as `|` blocks so the YAML stays readable."""
    if "\n" in data:
        # Trailing spaces make a literal block illegal — strip them per line.
        data = "\n".join(line.rstrip() for line in data.split("\n"))
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(str, _block_style_str)


def main() -> int:
    spec = build_spec()
    OUTPUT.write_text(
        "# GENERATED FILE — do not edit.\n"
        "# Regenerate with: python3 contract/generate_contract.py\n"
        + yaml.dump(spec, Dumper=_Dumper, sort_keys=False,
                    allow_unicode=True, width=100)
    )
    print(f"Wrote {OUTPUT.relative_to(Path.cwd())}"
          if OUTPUT.is_relative_to(Path.cwd()) else f"Wrote {OUTPUT}")
    print(f"  {len(spec['paths'])} commands, "
          f"{len(spec['components']['schemas'])} schemas")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
